_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
best_C:
    value: 100
best_max_iter:
    value: 1000
best_solver:
    value: lbfgs
initial_C:
    value:
        - 0.01
        - 0.1
        - 1
        - 10
        - 100
initial_max_iter:
    value:
        - 1000
        - 5000
        - 10000
initial_solver:
    value:
        - lbfgs
        - saga
        - newton-cg
model_type:
    value: Logistic Regression
