_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 5
                - 50
                - 53
                - 55
            "2":
                - 5
                - 50
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
data:
    value: '{''path'': ''data.csv''}'
model:
    value: '{''name'': ''logistic_regression'', ''logistic_regression'': {''C'': 1.0, ''solver'': ''lbfgs'', ''max_iter'': 5000}, ''random_forest'': {''n_estimators'': 100, ''max_depth'': None}, ''knn'': {''n_neighbors'': 5, ''weights'': ''uniform''}}'
training:
    value: '{''epochs'': 10}'
